import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;

public class ParchiGenerator {

    public String generateReceipt(BillCalculator.SplitResult result, String mode) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd MMM yyyy, hh:mm a");
        String dateTime = LocalDateTime.now().format(formatter);

        String receipt = "";

        receipt += "=== DOST BILL SPLITTER ===\n";
        receipt += "~ Split fair, stay friends ~\n";
        receipt += "----------------------------\n";
        receipt += "Date: " + dateTime + "\n";
        receipt += "Mode: " + mode + "\n";
        receipt += "People: " + result.getPeople() + "\n";
        receipt += "----------------------------\n";

        ArrayList<BillCalculator.ItemEntry> items = result.getItems();
        if (items != null && items.size() > 0) {
            receipt += "ITEMS:\n";
            for (int i = 0; i < items.size(); i++) {
                receipt += " " + (i + 1) + ". [" + items.get(i).getPersonName() + "] "
                        + items.get(i).getName()
                        + " - PKR " + String.format("%,.2f", items.get(i).getPrice()) + "\n";
            }
            receipt += "----------------------------\n";
        }

        receipt += "Subtotal:     PKR " + String.format("%,.2f", result.getSubtotal()) + "\n";
        receipt += "GST (16%):    PKR " + String.format("%,.2f", result.getGstAmount()) + "\n";

        if (result.getTipAmount() > 0) {
            receipt += "Tip:          PKR " + String.format("%,.2f", result.getTipAmount()) + "\n";
        }

        receipt += "----------------------------\n";
        receipt += "GRAND TOTAL:  PKR " + String.format("%,.2f", result.getGrandTotal()) + "\n";

        if (result.getPersonTotals() != null && !result.getPersonTotals().isEmpty()) {
            receipt += "============================\n";
            receipt += "EACH PERSON PAYS:\n";
            for (int i = 0; i < result.getPersonTotals().size(); i++) {
                BillCalculator.PersonTotal pt = result.getPersonTotals().get(i);
                receipt += " " + pt.getPersonName() + ": PKR " + String.format("%,.2f", pt.getGrandTotal()) + "\n";
            }
            receipt += "============================\n";
        } else {
            receipt += "============================\n";
            receipt += "EACH PERSON PAYS: PKR " + String.format("%,.2f", result.getPerPerson()) + "\n";
            receipt += "============================\n";
        }

        receipt += "Generated by Dost Bill Splitter\n";

        return receipt;
    }

    public String generateAndCopy(BillCalculator.SplitResult result, String mode) {
        String receipt = generateReceipt(result, mode);
        copyToClipboard(receipt);
        return receipt;
    }

    public void copyToClipboard(String text) {
        StringSelection selection = new StringSelection(text);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(selection, null);
    }
}
